name: release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      pypi:
        description: "Publish to PyPI"
        required: false
        default: true
        type: boolean

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    env:
      {% raw %}GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}{% endraw %}
    steps:
      - uses: actions/checkout@v4
      - name: Check most recent test run on `main`
        id: latest-test-result
        run: |
          echo "result=$(gh run list \
                          --branch=main \
                          --workflow=test.yml \
                          --json headBranch,workflowName,conclusion \
                          --jq '.[] | select(.headBranch=="main" and .conclusion=="success") | .conclusion' \
                          | head -n 1)" >> $GITHUB_OUTPUT
      - name: OK
        {% raw %}if: ${{ (contains(steps.latest-test-result.outputs.result, 'success')) }}{% endraw %}
        run: |
          exit 0
      - name: Fail
        {% raw %}if: ${{ !contains(steps.latest-test-result.outputs.result, 'success') }}{% endraw %}
        run: |
          exit 1


  pypi:
    {% raw %}if: ${{ github.event_name == 'release' || inputs.pypi }}{% endraw %}
    runs-on: ubuntu-latest
    needs: check
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "{cookiecutter.python_max_version}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch

      - name: Build package
        run: |
          hatch build

      {% raw %}- if: ${{ github.event_name == 'workflow_dispatch' }}{% endraw %}
        name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      {% raw %}- if: ${{ github.event_name != 'workflow_dispatch' }}{% endraw %}
        name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
