name: release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      pypi:
        description: "Publish to PyPI"
        required: false
        default: true
        type: boolean

jobs:
  pypi:
    {% raw %}if: ${{ github.event_name == 'release' || inputs.pypi }}{% endraw %}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "{cookiecutter.python_max_version}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch

      - name: Build package
        run: |
          hatch build

      {% raw %}- if: ${{ github.event_name == 'workflow_dispatch' }}{% endraw %}
        name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      {% raw %}- if: ${{ github.event_name != 'workflow_dispatch' }}{% endraw %}
        name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
